<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Shopping cart template
 *
 * @var $block \Magento\Checkout\Block\Cart
 */

// $objectManager = \Magento\Framework\App\ObjectManager::getInstance();

// $slct_options = $objectManager->create("Magento\Framework\Registry")->registry('orderData');
// echo "<pre>";
// print_r($slct_options->getData());


if ($block->getItemsCount()) {
    echo $block->getChildHtml('with-items');
} else {
    echo $block->getChildHtml('no-items');
}
